### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by niicojs** [dracoapi/dracowalker#4]
- [x]  Update routers so it goes to chest if they see one
- [ ]  You can be attack by wild creature? I don't handle that
- [ ]  Auto evolve creature (on what logic?)
- [ ]  Mother of Dragons
- [x]  Log loot
- [x]  Auto evolve perfect creatures

**Comment by sirlygo** [comment]
Auto evolve at 100%

**Comment by Nackenschelle** [comment]
Auto Level up 100% iv
